
default:
	@echo portaudio/asio
	@cd asio
	@$(MAKE)
	@echo portaudio/win
	@cd ../win
	@$(MAKE)
	@cd ..

clean:
	@echo portaudio/asio
	@cd asio
	@$(MAKE) clean
	@echo portaudio/win
	@cd ..\win
	@$(MAKE) clean
	@cd ..
